name: data-fetch-and-deploy

on:
  push:
    branches:
      - main
  schedule:
    # https://crontab.guru/#30_0_*_*_*
    # - cron: '25 0,1 * * *'
env:
  TZ: Asia/Shanghai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm run fetch

    - uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.PAGES_DEPLOY_TOKEN }}
        BRANCH: gh-pages
        FOLDER: data
        CLEAN: true
